// @ts-nocheck
import { test } from 'node:test'; import assert from 'node:assert/strict'; import { testDb,testConfig,makeAthlete,fixedClock,collectingLogger,NOW } from '../support/factories.js'; import { createAthleteStore } from '../../src/adapters/store/athletes.js'; import { createActivityStore } from '../../src/adapters/store/activities.js'; import { createInviteStore } from '../../src/adapters/store/invites.js'; import { createAuthStateStore } from '../../src/adapters/store/authStates.js'; import { createSessions } from '../../src/web/session.js'; import { createApp } from '../../src/web/app.js'; import { request,form } from '../support/app.js';
function setup(){const db=testDb(),config=testConfig(),athleteStore=createAthleteStore(db),activityStore=createActivityStore(db),invites=createInviteStore(db),authStates=createAuthStateStore(db),sessions=createSessions(config.sessionSecret),logger=collectingLogger();const deletions=[];const dataDeletionService={async deleteAthleteData(athleteId,context){deletions.push({athleteId,...context});athleteStore.remove(athleteId);}};const app=createApp({config,athleteStore,activityStore,inviteStore:invites,authStateStore:authStates,dispatcher:{dispatch(){},drain:async()=>{}},sessions,connectService:{async completeConnect(){return{athleteId:987654,isNew:true};}},athleteService:{updateMessage(){return{ok:true};}},dataDeletionService,clock:fixedClock(NOW),logger});return{db,config,athleteStore,invites,authStates,sessions,app,deletions};}
test('homepage introduces goal sharing on Strava and directs existing athletes to log in',async()=>{const {app}=setup();const response=await request(app,'/');assert.equal(response.status,200);const body=await response.text();assert.match(body,/Run for it\.\s*<br>Share <em>why/i);assert.match(body,/Strava/i);assert.match(body,/How it works/i);assert.match(body,/href="\/login"/);assert.match(body,/href="\/privacy"/);});
test('app icon is served for the homepage header',async()=>{const {app}=setup();const response=await request(app,'/app-icon.png');assert.equal(response.status,200);assert.match(response.headers.get('content-type')??'',/^image\/png/);});
test('connect page is invite gated, empty by default, and records pending message in OAuth state',async()=>{const {app,invites,authStates}=setup();invites.create({token:'valid',now:NOW,expiresAt:NOW+60});const page=await (await request(app,'/connect?invite=valid')).text();assert.match(page,/<textarea[^>]*name="message"[^>]*><\/textarea>/);assert.match(page,/Synced via runsync/);assert.match(page,/\/privacy/);const response=await request(app,'/connect',form({invite:'valid',message:'Mine',consent:'on'}));assert.equal(response.status,302);const state=new URL(response.headers.get('location')).searchParams.get('state');assert.equal(authStates.consume(state,NOW)?.pending_message,'Mine');});
test('POST /connect without the consent checkbox is rejected and creates no OAuth state row',async()=>{const {app,db,invites}=setup();invites.create({token:'valid',now:NOW,expiresAt:NOW+60});const response=await request(app,'/connect',form({invite:'valid',message:'Mine'}));assert.equal(response.status,400);const body=await response.text();assert.match(body,/privacy notice/i);assert.match(body,/value="Mine"|>Mine</,'the athlete\'s message must survive the error re-render');assert.equal(db.prepare('SELECT COUNT(*) AS n FROM oauth_states').get().n,0);});
test('OAuth callback sets a secure session cookie',async()=>{const {app,sessions}=setup();const response=await request(app,'/oauth/callback?code=c&state=s&scope=activity%3Aread%20activity%3Awrite');assert.equal(response.status,302);const cookie=response.headers.get('set-cookie')??'';assert.match(cookie,/HttpOnly/);assert.equal(sessions.verify(decodeURIComponent(cookie.split(';')[0].split('=')[1]??''),NOW),987654);});
test('dashboard requires a session and uses the athlete override field',async()=>{const {app,db,sessions}=setup();makeAthlete(db,{message:'Mine'});const cookie=`${sessions.COOKIE_NAME}=${encodeURIComponent(sessions.sign(987654,NOW+60))}`;assert.equal((await request(app,'/dashboard')).status,302);const body=await (await request(app,'/dashboard',{headers:{cookie}})).text();assert.match(body,/<textarea[^>]*>Mine<\/textarea>/);assert.match(body,/future activities only/i);assert.match(body,/\/privacy/);});
test('POST /delete-account erases the athlete and clears the session',async()=>{const {app,db,athleteStore,sessions,deletions}=setup();makeAthlete(db);const cookieValue=sessions.sign(987654,NOW+60);const cookie=`${sessions.COOKIE_NAME}=${encodeURIComponent(cookieValue)}`;const csrf=sessions.csrfToken(cookieValue);const {headers,body}=form({csrf});const response=await request(app,'/delete-account',{method:'POST',headers:{...headers,cookie},body});assert.equal(response.status,200);const responseBody=await response.text();assert.match(responseBody,/deleted/i);assert.deepEqual(deletions,[{athleteId:987654,reason:'user-request'}]);assert.equal(athleteStore.get(987654),undefined);assert.match(response.headers.get('set-cookie')??'',new RegExp(`${sessions.COOKIE_NAME}=;`));});
